/*
 * TemperatureController.cpp
 *
 *  Created on: Jan 14, 2023
 *      Author: Niuslar
 */

#include "main.h"
#include "cmsis_os2.h"
#include "etl/string.h"
#include "etl/to_string.h"
#include "CThermistor.h"
#include "adc.h"
#include "SystemConfig.h"

#ifdef __cplusplus
extern "C"
{
#endif

/* Controller variables */
CAdcData    adc1(&hadc1);

CThermistor thermistor1(TEMP_1_ADC_CH, &adc1);
CThermistor thermistor2(TEMP_2_ADC_CH, &adc1);
CThermistor thermistor3(TEMP_3_ADC_CH, &adc1);
CThermistor thermistor4(TEMP_4_ADC_CH, &adc1);
CThermistor thermistor5(TEMP_5_ADC_CH, &adc1);
CThermistor thermistor6(TEMP_6_ADC_CH, &adc1);
CThermistor thermistor7(TEMP_7_ADC_CH, &adc1);
CThermistor thermistor8(TEMP_8_ADC_CH, &adc1);

CThermistor *thermistors[TEMP_CHANNELS_COUNT] = {&thermistor1,
		&thermistor2,
		&thermistor3,
		&thermistor4,
		&thermistor5,
		&thermistor6,
		&thermistor7,
		&thermistor8
};


void TemperatureControllerInit()
{
	adc1.init();

}

void TemperatureControllerRun()
{
	uint32_t eventFlags = osEventFlagsGet(tempControlFlagsHandle);
	if(eventFlags & 1)
	{
		// We received a flag to read temperatures. Fill output queue with data
		osMessageQueueReset(messagesOutHandle);
		float temp1 = thermistor1.getTemperature();
		etl::string<MAX_STRING_SIZE> temps_string;
		etl::to_string(temp1, temps_string, true);
		osMessageQueuePut(messagesOutHandle, &temps_string, 1, 100);
		osEventFlagsClear(tempControlFlagsHandle,0xFFFFFFFF);
	}
	adc1.trigger();
}

class CTemperatureController: public CController
{
	public:
	CTemperatureController()
	{
		CLI_Command_Definition_t get_temperature_command
		{
			"?temperature",
			"?temperature: No arguments needed. Return current temperature on all sensors.\n",
			CTemperatureController::getTemperature
		}
		FreeRTOSRegisterCommand(get_temperature_command);
	}

	typedef struct xCOMMAND_LINE_INPUT
	{
		const char * const pcCommand;				/* The command that causes pxCommandInterpreter to be executed.  For example "help".  Must be all lower case. */
		const char * const pcHelpString;			/* String that describes how to use the command.  Should start with the command itself, and end with "\r\n".  For example "help: Returns a list of all the commands\r\n". */
		const pdCOMMAND_LINE_CALLBACK pxCommandInterpreter;	/* A pointer to the callback function that will return the output generated by the command. */
		int8_t cExpectedNumberOfParameters;			/* Commands expect a fixed number of parameters, which may be zero. */
	} CLI_Command_Definition_t;


	// this is a base type callback definition for each command
	static BaseType_t getTemperature( char *pcWriteBuffer,
	                             size_t xWriteBufferLen,
	                             const char *pcCommandString );

	static BaseType_t setTemperature( char *pcWriteBuffer,
	                             size_t xWriteBufferLen,
	                             const char *pcCommandString );


	//this will process all commands
	static BaseType_t processCommand( char *pcWriteBuffer,
	                             size_t xWriteBufferLen,
	                             const char *pcCommandString );

}



#ifdef __cplusplus
}
#endif


